spring:
  profiles:
    include: route    #其他yml引入
  application:
    name: service-gateway-8101
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: localhost:8848
        service: service-gateway-8101


server:
  port: 8101
